### ISSUE TITLE
Build isn't built for amd64

### ISSUE THREAD

**Issue by edouard** [webtranslateit/wti-docker#1]
https://hub.docker.com/r/webtranslateit/webtranslateit/tags

**Comment by debreczeniandras** [comment]
You may also use one of the slim ruby images. With ruby:2.5-slim-buster the size is already half of the original one. 
when using ruby:2.5-alpine3.13 as base your image is about 54MB.

**Comment by edouard** [comment]
Hey @debreczeniandras I’ll confess my knowledge and understanding of Docker and building containers is rather limited. I’ve managed to create a GitHub Action to publish new containers containing the wti rubygem to the GitHub Docker Registry.

I've just [built the version 2.6.3 of the gem](https://github.com/webtranslateit/wti-docker/pkgs/container/wti-docker) here.

I also built the package version 2.6.3.1 using the `ruby:2.6.6-alpine3.13` Alpine image, which should make a smaller container.

Can you let me know if it works for you? With this automated building we’ll release a new docker image each time we release a new version of the gem.

Thanks!

**Comment by debreczeniandras** [comment]
Works @edouard flawlessly. 
And the image is just 50.1Mb
Thanks a lot, great job.

**Comment by edouard** [comment]
Ok! We'll build using Alpine Linux going forward. Thanks a lot for your feedback!
